### ISSUE TITLE
Terminal isn't receiving input from keyboard.

### ISSUE THREAD

**Issue by Ev1lbl0w** [vigiloproject/vigilo#22]
Nothing shows up when I write something to the terminal. Fix quickly. Tested with Chrome and Firefox.

**Comment by FFY00** [comment]
You need to point your mouse cursor exactly to the terminal cursor and right click.

**Comment by Ev1lbl0w** [comment]
Thanks, but it stills needs to be fixed.

**Comment by FFY00** [comment]
Of course...
